version: "3"
services:
  n1:
    hostname: n1
    container_name: n1
    image: nats:2.11.8-alpine3.22
    environment:
      GATEWAY: c1
      NAME: n1.c1
    networks:
      - shared
      - nats-cluster1
    ports:
      - 10000:4222
    volumes:
      - ./cluster.n1.conf:/etc/nats/nats-server.conf
      - ./data/n1.c1:/data
  
  n2:
    hostname: n2
    container_name: n2
    image: nats:2.11.8-alpine3.22
    environment:
      GATEWAY: c1
      NAME: n2.c1
    networks:
      - shared
      - nats-cluster1
    ports:
      - 10001:4222
    volumes:
      - ./cluster.n2.conf:/etc/nats/nats-server.conf
      - ./data/n2.c1:/data
  
  n3:
    hostname: n3
    container_name: n3
    image: nats:2.11.8-alpine3.22
    environment:
      GATEWAY: c1
      NAME: n3.c1
    networks:
      - shared
      - nats-cluster1
    ports:
      - 10002:4222
    volumes:
      - ./cluster.n3.conf:/etc/nats/nats-server.conf
      - ./data/n3.c1:/data
  

networks:
  nats-cluster1: {}
  shared: {}
