services:
  nats-0:
    image: nats:latest
    container_name: nats-0
    command: "-c /config/nats.conf"
    ports:
      - "4222:4222"  # Client connections
      - "6222:6222"  # Cluster communication
      - "8222:8222"  # Monitoring UI
    volumes:
      - ./nats0/data:/data  # Store JetStream data on the host
      - ./nats0/config:/config #Sttore config file  
    networks:
      - nats-net

  nats-1:
    image: nats:latest
    container_name: nats-1
    command: "-c /config/nats.conf"
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
    volumes:
       - ./nats1/data:/data  # Store JetStream data on the host
       - ./nats1/config:/config #Sttore config file  
    networks:
      - nats-net

  nats-2:
    image: nats:latest
    container_name: nats-2
    command: "-c /config/nats.conf"
    ports:
      - "4224:4222"
      - "6224:6222"
      - "8224:8222"
    volumes:
       - ./nats2/data:/data  # Store JetStream data on the host
       - ./nats2/config:/config #Sttore config file  
    networks:
      - nats-net

networks:
  nats-net:
    driver: bridge
